---
openapi: 3.0.1
info:
  title: Pure FlashArray API
  description: |-
    # Confidential and Proprietary. Subject to NDA and End User Agreement. 
    

    # Authentication
    Use an API-Token to start a session, that returns an session cookie which expires in 30 minutes by default.

    ## Error Codes
    Use HTTP Response codes to determine command results.  Error message json formats are different depending on the endpoint.

    ## Best practices
    You may want to take a look at the [best practices docs here](https://support.purestorage.com/FlashArray/PurityFA/Purity_FA_REST_API/Reference/Pure_Storage_REST_API_Best_Practices). 
    
    ## Pagenation
    Pagenation/filtering information is not shown here.  However, it is available for some endpoints. Please see the PDF docs.


    ## Authenticate (uses API Key and returns a cookie)
    Use POST ../auth/session , and put in your API Key.  (to get API Key, you can do POST ../auth/apitoken with your user/pass) \
    This will return your API key, or you can get it from the Web UI.  After doing a POST ../auth/session, the array returns \
    a cookie which is handled by the browser which enables additional API calls.  Session cookies expire by default after 30 minutes.

    
servers:
- url: http://127.0.0.1/api/
  description: Local host, PureSwagger Proxy, set array IP at top of page.
paths:
  /api_version:
    get:
      description: Lists supported API versions on this array.
      responses:
        200:
          description: "List supported API versions"
      tags: [API]
tags:
- {description: List APIs, name: API}
components: 
  schemas: {}
  
  
