---
openapi: 3.0.1
info:
  title: Pure FlashArray API
  description: |-
    # Authentication
    Use an API-Token to start a session, that returns an session cookie which expires in 30 minutes by default.

    ## Error Codes
    Use HTTP Response codes to determine command results.  Error message json formats are different depending on the endpoint.

    ## Best practices
    You may want to take a look at the [best practices docs here](https://support.purestorage.com/FlashArray/PurityFA/Purity_FA_REST_API/Reference/Pure_Storage_REST_API_Best_Practices). 
    
    ## Pagenation
    Pagenation/filtering information is not shown heret.  However, it is available for some endpoints. Please see the PDF docs.

    # "Try it Out" (awesome feature!)

    ## CORS
    The Try will NOT work without a [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) bypass. \
    The ONLY browser that works reliable is firefox.  If you want the Try it out to work, please use firefox.
    For Firefox [CORS Everywhere](https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/) \ 
    
    Try It Out **WILL NOT** work without a CORS bypass plugin.  (If anyone can get chrome to work please let me know and I'll include those instructions. 
    I have not been able to find any extension that works to bypass CORS on Chrome.) 

    ## IP
    Next, put in your Array IP where it says change me below.  

    ## Accept Security Certificate
    Open your array IP in a new tab on your browser and accept the security certificate and ensure you can reach it's IP/hostname.

    ## Test connectivity
    Test /api_version  - If this fails retry the steps above.

    ## Authenticate 
    Use POST ../auth/session , and put in your API Key.  (to get API Key, you can do POST ../auth/apitoken with your user/pass) \
    This will re
    Then you can do any other API call

    
servers:
- url: https://{hostname}/api/
  description: Your FlashArray IP/Hostname
  variables:
    hostname:
      description: The FQDN or IP of the array
      default: change-me
paths:
  /api_version:
    get:
      description: Lists supported API versions on this array.
      responses:
        200:
          description: "List supported API versions"
      tags: [API]
tags:
- {description: List APIs, name: API}
components: 
  schemas: {}
  
  
